### ISSUE TITLE
Rayon library evaluation tracking issue

### ISSUE THREAD

**Issue by alexcrichton** [rayon-rs/rayon#433]
* [ ] [Comment "std-like" modules why they are the way they are](https://github.com/nikomatsakis/rayon/issues/414)
* [x] [Rename/move the iter::internal module](https://github.com/nikomatsakis/rayon/issues/415)
* [x] [Implement `Clone` for iterators where possible](https://github.com/nikomatsakis/rayon/issues/416)
* [ ] [Move to concrete Send/Sync error type](https://github.com/nikomatsakis/rayon/issues/417)
* [x] [doc: Add crate-level documentation](https://github.com/nikomatsakis/rayon/issues/418)
* [x] [doc: Examples should use `?` not `try!`](https://github.com/nikomatsakis/rayon/issues/419)
* [ ] [doc: Documentation examples for parallel iterator methods](https://github.com/nikomatsakis/rayon/issues/420)
* [ ] [doc: Modules should have documentation](https://github.com/nikomatsakis/rayon/issues/421)
* [ ] [doc: Structures/types should all be documented](https://github.com/nikomatsakis/rayon/issues/422)
* [x] [doc: Missing attributes in Cargo.toml](https://github.com/nikomatsakis/rayon/issues/423)
* [x] [doc: Crate missing `html_root_url` attribute](https://github.com/nikomatsakis/rayon/issues/424)
* [x] ~~[Configuration uses `self` instead of `&mut self`](https://github.com/nikomatsakis/rayon/issues/425)~~
* [x] [Configuration doesn't have a "build" method](https://github.com/nikomatsakis/rayon/issues/426)
* [x] [Public types should implement `Debug`](https://github.com/nikomatsakis/rayon/issues/427)
* [ ] [Add an unsafe method to rayon-core to enable `rayon-futures`](https://github.com/nikomatsakis/rayon/issues/428)
* [ ] [Consider adding a rayon-itertools crate](https://github.com/nikomatsakis/rayon/issues/429)
* [x] [`Scope::spawn` doesn't require `Send`](https://github.com/nikomatsakis/rayon/issues/430)
* [ ] [rayon::spawn should document the lack of return value](https://github.com/nikomatsakis/rayon/issues/431)
* [x] [rayon::split available also at rayon::iter::split](https://github.com/nikomatsakis/rayon/issues/432)
* [ ] Bump rayon to 1.0

**Comment by nikomatsakis** [comment]
Going to close this since is duplicates the 1.0 milestone.
